### ISSUE TITLE
Breaking change(s) in new version of fastshap

### ISSUE THREAD

**Issue by bgreenwell** [myles-lewis/nestedcv#20]
Hi @myles-lewis,

I am preparing a new release of [fastshap](https://github.com/bgreenwell/fastshap) for CRAN, and it seems like it will break some functionality in your package. You can see a list of changes [here](https://github.com/bgreenwell/fastshap/blob/master/NEWS.md). I suspect the biggest changes affecting your package iare that 1) **fastshap** >= 0.1.0 will no longer return a tibble, but rather a matrix, and 2) the `autoplot()` function have been removed in favor of using the much better [shapviz](https://cran.r-project.org/package=shapviz) package.

Just wanted to give you a heads up before I plan to submit in two weeks.

# nestedcv

<details>

* Version: 0.6.1
* GitHub: https://github.com/myles-lewis/nestedcv
* Source code: https://github.com/cran/nestedcv
* Date/Publication: 2023-04-16 08:20:03 UTC
* Number of recursive dependencies: 174

Run `revdepcheck::revdep_details(, "nestedcv")` for more info

</details>

## Newly broken

*   checking examples ... ERROR
    ```
    Running examples in ‘nestedcv-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: pred_nestcv_glmnet
    > ### Title: Prediction wrappers to use fastshap with nestedcv
    > ### Aliases: pred_nestcv_glmnet pred_nestcv_glmnet_class1
    > ###   pred_nestcv_glmnet_class2 pred_nestcv_glmnet_class3 pred_train
    > ###   pred_train_class1 pred_train_class2 pred_train_class3
    > 
    > ### ** Examples
    ...
    Error in `autoplot()`:
    ! Objects of class <explain> are not supported by autoplot.
    ℹ have you loaded the required package?
    Backtrace:
        ▆
     1. ├─ggplot2::autoplot(sh)
     2. └─ggplot2:::autoplot.default(sh)
     3.   └─cli::cli_abort(...)
     4.     └─rlang::abort(...)
    Execution halted
    ```

**Comment by myles-lewis** [comment]
Dear Brandon,
Thanks. I will take a look and prepare a fix.
All the best, Myles

From: Brandon Greenwell ***@***.***>
Date: Thursday, 11 May 2023 at 14:03
To: myles-lewis/nestedcv ***@***.***>
Cc: Myles Lewis ***@***.***>, Mention ***@***.***>
Subject: [myles-lewis/nestedcv] Breaking change(s) in new version of fastshap (Issue #20)

Hi @myles-lewis<https://github.com/myles-lewis>,

I am preparing a new release of fastshap<https://github.com/bgreenwell/fastshap> for CRAN, and it seems like it will break some functionality in your package. You can see a list of changes here<https://github.com/bgreenwell/fastshap/blob/master/NEWS.md>. I suspect the biggest change affecting your package is that fastshap >= 0.1.0 will no longer return a tibble, but rather a matrix.

Just wanted to give you a heads up before I plan to submit in two weeks.

nestedcv

  *   Version: 0.6.1
  *   GitHub: https://github.com/myles-lewis/nestedcv
  *   Source code: https://github.com/cran/nestedcv
  *   Date/Publication: 2023-04-16 08:20:03 UTC
  *   Number of recursive dependencies: 174

Run revdepcheck::revdep_details(, "nestedcv") for more info

Newly broken

  *   checking examples ... ERROR

·         Running examples in ‘nestedcv-Ex.R’ failed

·         The error most likely occurred in:

·

·         > ### Name: pred_nestcv_glmnet

·         > ### Title: Prediction wrappers to use fastshap with nestedcv

·         > ### Aliases: pred_nestcv_glmnet pred_nestcv_glmnet_class1

·         > ###   pred_nestcv_glmnet_class2 pred_nestcv_glmnet_class3 pred_train

·         > ###   pred_train_class1 pred_train_class2 pred_train_class3

·         >

·         > ### ** Examples

·         ...

·         Error in `autoplot()`:

·         ! Objects of class <explain> are not supported by autoplot.

·         ℹ have you loaded the required package?

·         Backtrace:

·             ▆

·          1. ├─ggplot2::autoplot(sh)

·          2. └─ggplot2:::autoplot.default(sh)

·          3.   └─cli::cli_abort(...)

·          4.     └─rlang::abort(...)

·         Execution halted

**Comment by myles-lewis** [comment]
Should be fixed in next version. I removed call to `autoplot()` completely.
