### ISSUE TITLE
predSummary with multiclass classification

### ISSUE THREAD

**Issue by gagirob** [myles-lewis/nestedcv#38]
When dealijng with multiclass classification, the row
b_acc <- ccm$byClass[11]
in predSummary.R (line 51) should read
b_acc <- ccm$byClass[,11]
and following edits should take this into account.

Thank you.

**Comment by myles-lewis** [comment]
Thanks. I've modified the code. This line is correct for binary class but as you point out, needs fixing for multi-class. The results for multi-class balanced accuracy are now expanded and have an entry for each class. Try installing the GitHub version now.

**Comment by myles-lewis** [comment]
Further modification to change the calculation to a single value for multi-class balanced accuracy. This is now calculated as the mean of the Recall for each class.
