### ISSUE TITLE
Possible logic error with inner_folds in nestcv.train?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [myles-lewis/nestedcv#40]
I was reading the code of `nestcv.train` and I noticed this line: https://github.com/myles-lewis/nestedcv/blob/main/R/nestcv.train.R#L278C7-L278C111

Currently it says:

```R
if (n_inner_folds != length(inner_folds)) stop("Mismatch between n_inner_folds and length(inner_folds)")
```

but I think it should say:

```R
if (n_inner_folds != length(inner_folds[[1]])) stop("Mismatch between n_inner_folds and length(inner_folds)")
```

I haven't had a chance to test this yet, but I will be soon, since I have a situation where I need to manually generate both outer and inner folds. My expectation is that the code in its current state will always throw an error if `length(inner_folds[[1]]) != length(inner_folds)`.

**Comment by myles-lewis** [comment]
Hi @DarwinAwardWinner 

I think you are correct. I've pushed the fix you suggested to main.

Thanks!
Best, Myles
